template: Hello, %s!

defaultName: ${DW_DEFAULT_NAME:-cloudcentrik-developer}

# Database settings.
database:

  # the name of your JDBC driver
  #driverClass: org.h2.Driver
  driverClass: org.postgresql.Driver

  # the username
  #user: sa
  #user: dagenslunch_admin
  user: ${JDBC_DATABASE_USERNAME}

  # the password
  #password: sa
  #password: open123
  password: ${JDBC_DATABASE_PASSWORD}

  # the JDBC URL
  #url: jdbc:h2:./target/example
  #url: jdbc:postgresql://localhost:5432/dagenslunchdb
  url: ${JDBC_DATABASE_URL}
  
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# use the simple server factory if you only want to run on a single port
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
    

# Logging settings.
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: # TODO

#commandline commands
#data migration
#java -jar target/dagenslunch-1.1.0-SNAPSHOT.jar db migrate config.yml
#running server
#java -jar target/dagenslunch-1.1.0-SNAPSHOT.jar server config.yml